name: museu_vivo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  dio: ^3.0.9
  provider: ^4.1.2
  flutter_mobx: ^1.1.0
  mobx: ^1.2.1
  flutter_modular: ^1.2.5+1

  # Para gerenciamento da sessão do banco de dados offline
  # hive: ^1.0.0
  # hive_flutter: ^0.2.1
  # path_provider: ^1.2.0
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.9

  # Captura de fotos e seleção de imagens na galeria
  image_picker: ^0.6.7

  # Gravação e captura de áudio
  flutter_audio_recorder: ^0.5.5
  audioplayers: ^0.15.1

  # Trabalhar com geolocalização
  # geolocator: ^5.2.1
  geolocator: ^5.3.1

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  hive_generator: ^0.5.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/leratos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins-Bold.ttf
          weight: 700

    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa.ttf

    - family: PTSans
      fonts:
        - asset: fonts/PTSans-Regular.ttf
        - asset: fonts/PTSans-Bold.ttf
          weight: 700

    - family: Merriweather
      fonts:
        - asset: fonts/Merriweather-Regular.ttf

    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: SourceSerifPro
      fonts:
        - asset: fonts/SourceSerifPro-Regular.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: true
  ios: true
  image_path: "assets/leratos/icon.png"

scripts:
  build: flutter packages pub run build_runner build --delete-conflicting-outputs
  clean: flutter packages pub run build_runner clean
  watch: flutter packages pub run build_runner watch --delete-conflicting-outputs
  